Blog.Web/Areas/Admin/Controllers/HomeController.cs
using Blog.Entity.Entities;
using Blog.Service.Services.Abstractions;
using Microsoft.AspNetCore.Identity;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Blog.Web.Areas.Admin.Controllers
{
    //önyüzde de HomeController olduğu için bunun areasını belirtmem gerekiyor
    [Area("Admin")]
    [Authorize]
    public class HomeController : Controller
    {
        private readonly IArticleService articleService;
        private readonly IDashboardService dashboardService;

        public HomeController(IArticleService articleService,IDashboardService dashboardService)
        {
            this.articleService = articleService;
            this.dashboardService = dashboardService;
        }
        public async Task<IActionResult> Index()
        {
            var articles=await articleService.GetAllArticleWithCategoryNonDeletedAsync();
            return View(articles);
        }

        [HttpGet]
        public async Task<IActionResult> YearlyArticleCounts()
        {
            var count = await dashboardService.GetYearlyArticleCounts();
            return Json(JsonConvert.SerializeObject(count)); //dizi olarak yollamamız için serializeObjecti yapmamız gerekiyor
        }

        [HttpGet]
        public async Task<IActionResult> TotalArticleCount()
        {
            var count = await dashboardService.GetTotalArticleCount();
            return Json(count); //dizi olarak yollamamız için serializeObjecti yapmamız gerekiyor
        }

        [HttpGet]
        public async Task<IActionResult> TotalCategoryCount()
        {
            var count = await dashboardService.GetTotalCategoryCount();
            return Json(count); //dizi olarak yollamamız için serializeObjecti yapmamız gerekiyor
        }

    }
}

Blog.Web/Controllers/HomeController.cs
using Blog.Service.Services.Abstractions;
using Blog.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Blog.Web.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;
		private readonly IArticleService articleService;

		public HomeController(ILogger<HomeController> logger,IArticleService articleService)
		{
			_logger = logger;
			this.articleService = articleService;
		}

        [HttpGet]
        public async Task<IActionResult> Index(Guid? categoryId,int currentPage=1,int pageSize=3,bool isAscending=false)
		{
			var articles=await articleService.GetAllByPagingAsync(categoryId,currentPage,pageSize,isAscending);	
			return View(articles);
		}

		[HttpGet]
        public async Task<IActionResult> Search(string keyword, int currentPage = 1, int pageSize = 3, bool isAscending = false)
        {
            var articles = await articleService.SearchAsync(keyword, currentPage, pageSize, isAscending);
            return View(articles);
        }

        public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}

		public async Task<IActionResult> Detail(Guid id)
		{
			var article = await articleService.GetArticleWithCategoryNonDeletedAsync(id);

			return View(article);

		}
	}
}

Blog.Web/ViewComponents/HomeCategoriesViewComponent.cs
using Blog.Service.Services.Abstractions;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Web.ViewComponents
{
    public class HomeCategoriesViewComponent :ViewComponent
    {
        private readonly ICategoryService categoryService;

        public HomeCategoriesViewComponent(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }
        public async Task<IViewComponentResult> InvokeAsync() 
        {
            var categories = await categoryService.GetAllCategoriesNonDeletedTake24();
            return View(categories);
        }
    }
}

Blog.Web/Views/Home/Detail.cshtml
@{
}
@model ArticleDto


<section class="blog-posts">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="all-blog-posts">
                    <div class="row">
                        <div class="col-lg-12">

                            <div class="blog-post">
                                <div class="blog-thumb w-50">
                                    <img src="~/images/@Model.Image.FileName" width="300" height="500" alt="resim bulunamadı" />
                                </div>
                                <div class="down-content">
                                    <a href="#"><h4>@Model.Title</h4></a>
                                    <ul class="post-info">
                                        <li>@Model.CreatedDate.ToString("dd/MM/yyyy")</li>
                                    </ul>
                                    <textarea type="text" class="form-control textarea-autosize" rows="25" > @Model.Content </textarea>
                                   
                                    <div class="post-options">
                                        <div class="row">
                                            <div class="col-6">
                                                <ul class="post-tags">
                                                    <li><i class="fa fa-tags"></i></li>
                                                    <li><a href="#">@Model.category.Name</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Blog.Web/Views/Home/Index.cshtml
@model ArticleListDto

<section class="blog-posts">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="all-blog-posts">
                    <div class="row">
                        <div class="col-lg-12 " width="100">
                            @foreach (var item in Model.Articles)
                            {
                                <input type="hidden" id="keyword" value="@Model.CurrentPage"/>
                                <div class="blog-post">
                                    <div class="blog-thumb h-50">
                                        <img src="~/images/@item.Image.FileName" class="w-75 " alt="resim bulunamadı" />

                                    </div>
                                    <div class="down-content h-50">
                                        <!--asp-route ile gösterilen actiona a id yi yolluyorum -->
                                        <a asp-controller="Home" asp-action="Detail" asp-route-id="@item.Id"><h4>@item.Title</h4></a>
                                        <ul class="post-info">
                                            <!--<li></li> -->
                                            <li>@item.CreatedDate.ToString("dd/MM/yyyy")</li>
                                            <!--<li><i class="fa-solid fa-eye"></i> </li> -->
                                        </ul>
                                        <p>
                                            @(item.Content.Length > 280 ? item.Content.Substring(0, 280) : item.Content) ...
                                        </p>
                                        <div class="post-options">
                                            <div class="row">
                                                <div class="col-6">
                                                    <ul class="post-tags">
                                                        <li><i class="fa fa-tags"></i></li>
                                                        <li><a href="#">@item.category.Name</a></li>
                                                    </ul>
                                                </div>
                                                <div class="col-6">
                                                    <ul class="post-share">
                                                        <li><i class="fa fa-link"></i></li>
                                                        <li><a asp-controller="Home" asp-action="Detail" asp-route-id="@item.Id">[Devamını Oku]</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                        <div class="col-lg-12">
                            @*<div class="main-button">
                            <a href="blog.html">View All Posts</a>
                            </div>*@

                          <ul class="pagination justify-content-center mb-4 mt-4 btn-block">

                                @if (Model.ShowPrevious)
                                {
                                    <li class="page-item">
                                        <a class="page-link" asp-route-currentPage="@(Model.CurrentPage - 1)" asp-route-pageSize="@Model.PageSize"> Önceki </a>
                                    </li>
                                }
                                @for (int i = 1; i < Model.TotalPages; i++)
                                {
                                    <li class="page-item @(i == Model.CurrentPage ? "active" : "")">

                                        <a class="page-link" asp-route-currentPage="@i" asp-route-pageSize="@Model.PageSize"> @i </a>
                                    </li>
                                }
                                @if (Model.ShowNext)
                                {
                                    <li class="page-item">
                                        <a class="page-link" asp-route-currentPage="@(Model.CurrentPage + 1)" asp-route-pageSize="@Model.PageSize"> Sonraki </a>
                                    </li>
                                }

                            </ul>


                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="sidebar">
                    <div class="row">
                        <!--
                        <div class="col-lg-12 d-none d-lg-block">
                            <div class="sidebar-item search">
                                <form id="search_form" asp-controller="Home" asp-action="Search" method="GET">
                                    <input type="text" name="keyword" class="searchText text-lowercase" placeholder="Arama yapınız..." autocomplete="on">
                                </form>
                            </div>
                        </div>
                        -->
                        <div class="col-lg-12 ">
                            <div class="sidebar-item categories">
                                <div class="sidebar-heading ">
                                    <h2 class="text-success ps-5">KATEGORİLER</h2>
                                </div>
                                @await Component.InvokeAsync("HomeCategories")

                            </div>
                        </div>
                        <div class="col-lg-12 d-none d-lg-block">
                            <div class="sidebar-item recent-posts">
                                <div class="sidebar-heading">
                                    <h2 class="text-success ps-5">LEZZET TURU</h2>
                                </div>

                                <div class="content">
                                    <ul>

                                        <li>
                                            <div class="row">
                                            <div class="col-6">
                                                    <img src="~/images/article-images/Pankek_449.jpg" class="" height="180" width="180" />

                                            </div>  
                                            <div class="col-6 m-auto">
                                                <a asp-controller="Home" asp-action="Search" class="badge rounded-pill bg-warning text-uppercase font-weight-bold h1 text-dark text-center ms-1" asp-route-keyword="PANKEK"> •PANKEK   </a>
                                            </div>

                                            </div>
                                        </li>


                                        <li>
                                            <div class="row">
                                                <div class="col-6">
                                                    <img src="~/images/article-images/PORTAKALLICHEESECAKE_16.jpg" height="180" width="180" class="" />

                                                </div>
                                                <div class="col-6 m-auto">
                                                    <a asp-controller="Home" asp-action="Search" class="badge rounded-pill bg-warning text-uppercase font-weight-bold h1 text-dark text-center ms-1" asp-route-keyword="PORTAKALLI CHEESECAKE"> •PORTAKALLI CHEESECAKE   </a>
                                        

                                                </div>

                                            </div>
                                        </li>


                                        <li>
                                            <div class="row">
                                                <div class="col-6">
                                                    <img src="~/images/article-images/KIYMALIPIRASAYEMEGI_744.jpg" height="180" width="180" class="" />

                                                </div>
                                                <div class="col-6 m-auto">
                                                    <a asp-controller="Home" asp-action="Search" class="badge rounded-pill bg-warning text-uppercase font-weight-bold h1 text-dark text-center ms-1" asp-route-keyword="KIYMALI PIRASA"> •KIYMALI PIRASA   </a>
                                        

                                                </div>

                                            </div>
                                        </li>

                                        <!--
                                        <li> <img src="~/images/article-images/MERCIMEKKOFTESI_175.jpg" class="w-25 h-25 img-fluid" /> <a asp-controller="Home" asp-action="Search" class="badge rounded-pill bg-warning w-50 text-uppercase font-weight-bold py-2 h2 text-dark py-3 display-4 ms-1" asp-route-keyword="MERCİMEK ÇORBASI"> •MERCİMEK ÇORBASI   </a> </li>
                                        <li> <img src="~/images/article-images/PORTAKALLICHEESECAKE_16.jpg" class="w-25 h-25" /><a asp-controller="Home" asp-action="Search" class="badge rounded-pill bg-warning w-50 text-uppercase font-weight-bold py-2 h2 text-dark py-3 display-4 ms-1" asp-route-keyword="BROKOLİ SALATASI"> •BROKOLİ SALATASI   </a> </li>
                                        <li>  <img src="~/images/article-images/KEREVIZSALATASI_48.jpg" class="w-25 h-25" /> <a asp-controller="Home" asp-action="Search" class="badge rounded-pill bg-warning w-50 text-uppercase font-weight-bold py-2 h2 text-dark py-3 display-4 ms-1" asp-route-keyword="PORTAKALLI CHEESECAKE"> •PORTAKALLI CHEESECAKE   </a> </li>

                                        -->





                                    </ul>






                                </div>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Blog.Web/Views/Home/Search.cshtml
@model ArticleListDto

<section class="blog-posts">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="all-blog-posts">
                    <div class="row">
                        <div class="col-lg-12">
                            @foreach (var item in Model.Articles)
                            {
                                <input type="hidden" id="keyword" value="@Model.CurrentPage" />
                                <div class="blog-post">
                                    <div class="blog-thumb">
                                        <img src="~/images/@item.Image.FileName" width="300" height="500" alt="resim bulunamadı" />
                                    </div>
                                    <div class="down-content">
                                        <a asp-controller="Home" asp-action="Detail" asp-route-id="@item.Id"><h4>@item.Title</h4></a>
                                        <ul class="post-info">
                                            <!--<li></li> -->
                                            <li>@item.CreatedDate.ToString("dd/MM/yyyy")</li>
                                            <!--<li><i class="fa-solid fa-eye"></i> </li> -->
                                        </ul>

                                        <textarea type="text" class="form-control textarea-autosize" rows="25"> @item.Content </textarea>

                                        <div class="post-options">
                                            <div class="row">
                                                <div class="col-6">
                                                    <ul class="post-tags">
                                                        <li><i class="fa fa-tags"></i></li>
                                                        <li><a href="#">@item.category.Name</a></li>
                                                    </ul>
                                                </div>
                                                <div class="col-6">
                                                   
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                        <div class="col-lg-12">
                            @*<div class="main-button">
                            <a href="blog.html">View All Posts</a>
                            </div>*@

                            <ul class="pagination justify-content-center mb-4 mt-4 btn-block">

                                @if (Model.ShowPrevious)
                                {
                                    <li class="page-item">
                                        <a class="page-link" asp-route-currentPage="@(Model.CurrentPage - 1)" asp-route-pageSize="@Model.PageSize"> Önceki </a>
                                    </li>
                                }
                                @for (int i = 1; i < Model.TotalPages; i++)
                                {
                                    <li class="page-item @(i == Model.CurrentPage ? "active" : "")">

                                        <a class="page-link" asp-route-currentPage="@i" asp-route-pageSize="@Model.PageSize"> @i </a>
                                    </li>
                                }
                                @if (Model.ShowNext)
                                {
                                    <li class="page-item">
                                        <a class="page-link" asp-route-currentPage="@(Model.CurrentPage + 1)" asp-route-pageSize="@Model.PageSize"> Sonraki </a>
                                    </li>
                                }

                            </ul>

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="sidebar">
                    <div class="row">
                        <div class="col-lg-12 d-none d-lg-block">
                            <div class="sidebar-item search">
                                <form id="search_form" asp-controller="Home" asp-action="Search" method="GET">
                                    <input type="text" name="keyword" class="searchText text-lowercase" placeholder="Arama yapınız..." autocomplete="on">
                                </form>
                            </div>
                        </div>

                        <div class="col-lg-12">
                            <div class="sidebar-item categories">
                                <div class="sidebar-heading ">
                                    <h2 class="text-success ps-5">KATEGORİLER</h2>
                                </div>
                                @await Component.InvokeAsync("HomeCategories")

                            </div>
                        </div>
                        <div class="col-lg-12 d-none d-lg-block">
                            <div class="sidebar-item recent-posts">
                                <div class="sidebar-heading">
                                    <h2 class="text-success ps-5">LEZZET TURU</h2>
                                </div>

                                <div class="content">
                                    <ul>

                                        <li>
                                            <div class="row">
                                                <div class="col-6">
                                                    <img src="~/images/article-images/Pankek_449.jpg" class="" height="180" width="180" />

                                                </div>
                                                <div class="col-6 m-auto">
                                                    <a asp-controller="Home" asp-action="Search" class="badge rounded-pill bg-warning text-uppercase font-weight-bold h1 text-dark text-center ms-1" asp-route-keyword="PANKEK"> •PANKEK   </a>
                                                </div>

                                            </div>
                                        </li>


                                        <li>
                                            <div class="row">
                                                <div class="col-6">
                                                    <img src="~/images/article-images/PORTAKALLICHEESECAKE_16.jpg" height="180" width="180" class="" />

                                                </div>
                                                <div class="col-6 m-auto">
                                                    <a asp-controller="Home" asp-action="Search" class="badge rounded-pill bg-warning text-uppercase font-weight-bold h1 text-dark text-center ms-1" asp-route-keyword="PORTAKALLI CHEESECAKE"> •PORTAKALLI CHEESECAKE   </a>


                                                </div>

                                            </div>
                                        </li>


                                        <li>
                                            <div class="row">
                                                <div class="col-6">
                                                    <img src="~/images/article-images/KIYMALIPIRASAYEMEGI_744.jpg" height="180" width="180" class="" />

                                                </div>
                                                <div class="col-6 m-auto">
                                                    <a asp-controller="Home" asp-action="Search" class="badge rounded-pill bg-warning text-uppercase font-weight-bold h1 text-dark text-center ms-1" asp-route-keyword="KIYMALI PIRASA"> •KIYMALI PIRASA   </a>


                                                </div>

                                            </div>
                                        </li>

                                        <!--
                                        <li> <img src="~/images/article-images/MERCIMEKKOFTESI_175.jpg" class="w-25 h-25 img-fluid" /> <a asp-controller="Home" asp-action="Search" class="badge rounded-pill bg-warning w-50 text-uppercase font-weight-bold py-2 h2 text-dark py-3 display-4 ms-1" asp-route-keyword="MERCİMEK ÇORBASI"> •MERCİMEK ÇORBASI   </a> </li>
                                        <li> <img src="~/images/article-images/PORTAKALLICHEESECAKE_16.jpg" class="w-25 h-25" /><a asp-controller="Home" asp-action="Search" class="badge rounded-pill bg-warning w-50 text-uppercase font-weight-bold py-2 h2 text-dark py-3 display-4 ms-1" asp-route-keyword="BROKOLİ SALATASI"> •BROKOLİ SALATASI   </a> </li>
                                        <li>  <img src="~/images/article-images/KEREVIZSALATASI_48.jpg" class="w-25 h-25" /> <a asp-controller="Home" asp-action="Search" class="badge rounded-pill bg-warning w-50 text-uppercase font-weight-bold py-2 h2 text-dark py-3 display-4 ms-1" asp-route-keyword="PORTAKALLI CHEESECAKE"> •PORTAKALLI CHEESECAKE   </a> </li>

                                        -->





                                    </ul>






                                </div>


                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
</section>